name = "rose-pine"
version = "0.1.8"
display-name = "Rosé Pine"
author = "ghishadow"
description = "Soho vibes for Lapce"
repository = "ghishadow/rose-pine-lapce"
themes = ["rose-pine.toml", "rose-pine-moon.toml", "rose-pine-dawn.toml"]
