name = "rose-pine"
version = "0.2.0"
display-name = "Rosé Pine"
author = "ghishadow"
description = "Soho vibes for Lapce"
repository = "ghishadow/rose-pine-lapce"
icon = "icon.png"
color-themes = ["rose-pine.toml", "rose-pine-moon.toml", "rose-pine-dawn.toml"]
